#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#define DRIVER_IN4_BACK D0
#define DRIVER_IN3_BACK D1
#define DRIVER_EN2_BACK_SPEED D2

#define DRIVER_IN2_FRONT D5
#define DRIVER_IN1_FRONT D6
#define DRIVER_EN1_FRONT_DIRECTION D7

#endif